AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless API Example Stack
Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${StackTagName} Environment ${EnvironmentTagName}
        - ResourceName: api
      StageName: !Ref EnvironmentAPIGatewayStageName
      DefinitionBody:
        swagger: '2.0'
        info: {}
        paths:
          /:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getWelcomePage.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
  getWelcomePage:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-getWelcomePage
      Description: !Sub
        - API Serveless Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: getWelcomePage
      CodeUri: src/getWelcomePage
      Handler: handler.handler
      Runtime: python3.10
      MemorySize: 3008
      Timeout: 30
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Events:
        apiGET:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref api
    Metadata:
      Name: getWelcomePage
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (defined at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (defined at deployment time)
  EnvironmentAPIGatewayStageName:
    Type: String
    Description: Environment name used for API Gateway Stage names (defined at deployment time)
